<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Film_model extends CI_Model
{

    public $table = 'film';
    public $id = 'id_film';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_film_comingsoon()
    {
      $sql="SELECT * FROM `film` where datediff(`tanggal_mulai`,NOW()) > 0";
      return $this->db->query($sql)->result();
    }

    function getJudulFilm(){//ambil film yang didalam rentang waktu tanggal selesai dengan tanggal mulai
      $sql="SELECT distinct `jadwal`.`id_film`,`film`.`judul_film`,`film`.`tanggal_selesai`,`film`.`tanggal_mulai`,DATEDIFF(`film`.`tanggal_selesai`,`film`.`tanggal_mulai`) as Hari,DATEDIFF(`film`.`tanggal_selesai`,NOW()) as DurasiHari,`film`.`url_gambar` FROM `jadwal`
      INNER JOIN `studio` ON `jadwal`.`id_studio`=`studio`.`id_studio`
      INNER JOIN `film` ON `jadwal`.`id_film`=`film`.`id_film`
      INNER JOIN `jam_tayang` ON `jadwal`.`id_jam_tayang`=`jam_tayang`.`id_jam_tayang`
      WHERE DATEDIFF(`film`.`tanggal_selesai`,NOW()) >0";
      return $this->db->query($sql)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_film', $q);
	$this->db->or_like('judul_film', $q);
	$this->db->or_like('tahun_produksi', $q);
	$this->db->or_like('sinopsis', $q);
	$this->db->or_like('durasi', $q);
	$this->db->or_like('tanggal_mulai', $q);
	$this->db->or_like('tanggal_selesai', $q);
	$this->db->or_like('url_gambar', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_film', $q);
	$this->db->or_like('judul_film', $q);
	$this->db->or_like('tahun_produksi', $q);
	$this->db->or_like('sinopsis', $q);
	$this->db->or_like('durasi', $q);
	$this->db->or_like('tanggal_mulai', $q);
	$this->db->or_like('tanggal_selesai', $q);
	$this->db->or_like('url_gambar', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Film_model.php */
/* Location: ./application/models/Film_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-10 22:05:15 */
/* http://harviacode.com */
