<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Masjid_model extends CI_Model
{

    public $table = 'masjid';
    public $id = 'id_masjid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all($id)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->where('id_dkm', $id);
        return $this->db->get($this->table)->result();
    }

    //get field
    function get_field(){
      return $this->db->list_fields($this->table);
    }


    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_masjid', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('url_foto', $q);
	$this->db->or_like('id_dkm', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_masjid', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('latitude', $q);
	$this->db->or_like('longitude', $q);
	$this->db->or_like('url_foto', $q);
	$this->db->or_like('id_dkm', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data,$id_dkm)
    {
        $this->db->where('id_dkm', $id_dkm);

  $query = $this->db->get($this->table);

  $count_row = $query->num_rows();

  if ($count_row > 0) {
    //if count row return any row; that means you have already this email address in the database. so you must set false in this sense.
      return FALSE; // here I change TRUE to false.
   } else {
     $this->db->insert($this->table, $data);
    // doesn't return any row means database doesn't have this email
      return TRUE; // And here false to TRUE
   }
    }


    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Masjid_model.php */
/* Location: ./application/models/Masjid_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-07-28 12:19:35 */
/* http://harviacode.com */
